---
platform: linux

image_resource:
  type: docker-image
  source: {repository:  broadinstitute/python-requests, tag: latest}
inputs:
- name: ci-source
- name: maven-output
run:
  path: python 
  args:
  - ci-source/scripts/python.py
