---
platform: linux

image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.6.3-jdk-8-slim}

inputs:
- name: project-source
- name: ci-source
caches:
- path: maven 
run:
  path: /bin/bash 
  args:
  - ci-source/scripts/maven-package.sh
outputs:
- name: maven-output
